package com.kzonix.spark;

import com.google.inject.Guice;
import com.google.inject.Module;
import com.kzonix.spark.module.AppModule;
import com.kzonix.spark.starter.ApplicationStarter;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SparkApplication {

  public static void run(Class<?> rootApplicationClass, String[] args) {
    final SparkApplication sparkApplication = new SparkApplication();
    sparkApplication.init(rootApplicationClass);
  }

  private void init(Class<?> rootApplicationClass) {
    Guice.createInjector(new AppModule())
        .getInstance(ApplicationStarter.class)
        .boot();
  }

  private void initGuice(List<? extends Module> modules) {

  }
}


