# This is a basic workflow to help you get started with Actions

name: Drone CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: DroneCI Build Trigger
        # You may pin to the exact commit or the version.
        # uses: kzonix/drone-ci-trigger@03d7df83e955a100e8a721cfe39de9b980822f1e
        uses: kzonix/drone-ci-trigger@0.0.2
        with:
          # URL of API for interacting with the Drone server. Example: http://localhost:8080/api
          droneApiUrl: 'http://drone.recursive-escalator.io/api'
          # Drone API Personal Token
          droneApiToken: 'TOKEN'
